// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"register_step2":{"path":"register_step2","id":"register_step2","parentId":"@@/global-layout","file":"register_step2.tsx"},"register_step3":{"path":"register_step3","id":"register_step3","parentId":"@@/global-layout","file":"register_step3.tsx"},"login_step2":{"path":"login_step2","id":"login_step2","parentId":"@@/global-layout","file":"login_step2.tsx"},"success":{"path":"success","id":"success","parentId":"@@/global-layout","file":"success.tsx"},"index":{"path":"/","id":"index","parentId":"@@/global-layout","file":"index.tsx"},"docs":{"path":"docs","id":"docs","parentId":"@@/global-layout","file":"docs.tsx"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.tsx","isLayout":true}},
    routeComponents: {
'register_step2': React.lazy(() => import(/* webpackChunkName: "src__pages__register_step2" */'../../../src/pages/register_step2.tsx')),
'register_step3': React.lazy(() => import(/* webpackChunkName: "src__pages__register_step3" */'../../../src/pages/register_step3.tsx')),
'login_step2': React.lazy(() => import(/* webpackChunkName: "src__pages__login_step2" */'../../../src/pages/login_step2.tsx')),
'success': React.lazy(() => import(/* webpackChunkName: "src__pages__success" */'../../../src/pages/success.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'docs': React.lazy(() => import(/* webpackChunkName: "src__pages__docs" */'../../../src/pages/docs.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
},
  };
}
